command: [
  "uvicorn",
  "app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000",
  "--workers",
  "8"
]

env:
  - name: DATABRICKS_TOKEN
    valueFrom: databricks-token
  - name: DATABRICKS_HOST
    value: "https://adb-7064161269814046.2.staging.azuredatabricks.net/"
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Shared/otel-traces-15"
  - name: UC_CATALOG_NAME
    value: "corey2"
  - name: UC_SCHEMA_NAME
    value: "m6"
  - name: UC_TABLE_PREFIX_NAME
    value: "otel-15"
