command: [
  "uvicorn",
  "app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000"
]

env:
  - name: DATABRICKS_TOKEN
    valueFrom: databricks-token
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Shared/otel-traces"
  - name: UC_CATALOG_NAME
    value: "main"
  - name: UC_SCHEMA_NAME
    value: "default"
  - name: UC_TABLE_PREFIX_NAME
    value: "otel"
