command: [
  "uvicorn",
  "app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000",
  "--workers",
  "8",
]

env:
  - name: DATABRICKS_TOKEN
    valueFrom: databricks-token
  - name: DATABRICKS_HOST
    value: "https://e2-dogfood.staging.cloud.databricks.com/"
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Shared/otel-traces5"
  - name: UC_CATALOG_NAME
    value: "corey2"
  - name: UC_SCHEMA_NAME
    value: "m6"
  - name: UC_TABLE_PREFIX_NAME
    value: "otel5"
